name = "pdoom"
main = "src/worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "pdoom"
database_id = "cf926c65-e204-41c2-8326-95243a7e9c07"

[vars]
GOOGLE_CLIENT_ID = "826189004528-0u8n3v3pap83f6i66csr1av2arv5qrmg.apps.googleusercontent.com"
APP_URL = "http://pdoom.workers.dev"
